cargo-features = ["edition2024"]

[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
lexer = { path = "../lexer" }
log = "0.4.27"
simple_logger = "5.0.0"
downcast-rs = "2.0.1"